### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by jerrymatjila** [zhengyuf/PointAvatar#1]
Thanks for the paper and release of the code. I attempted to perform evaluation on subject1 using 24GB RTX 3090. Changing train.max_points_training and point_cloud.max_points to 240000 or even lower values gives me CUDA out of memory.
Is there other parameters that can be used to avoid CUDA out of memory?

**Comment by zhengyuf** [comment]
hi, 

The max points parameters are to be set for training. Sorry I forgot to include the evaluation case:

For evaluation, by default the latest checkpoint is used. To reduce memory usage, you can use earlier checkpoints by adding —checkpoint 60 (or 55). Every 5th epoch, number of points is roughly doubled.

Yufeng

**Comment by jerrymatjila** [comment]
Thank you!
