### ISSUE TITLE
Any timeline to release animation parts？

### ISSUE THREAD

**Issue by ykk648** [zhengyuf/PointAvatar#12]

**Comment by zhengyuf** [comment]
It's already released..? or do you mean something else?

**Comment by ykk648** [comment]
Sorry for the confusing, I was evaluating this repo before, Aftering reading this link https://github.com/zhengyuf/PointAvatar/issues/2#issuecomment-1486420989 I raised an issue.

Perhaps I will reopen this issue after runing the codes.
