### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by TinBacon** [zhengyuf/PointAvatar#14]
I have followed your guidance, but still have a problem.

> Traceback (most recent call last):
>   File "/data/dingpeigeng/project/PointAvatar/code/scripts/exp_runner.py", line 51, in <module>
>     runner.run()
>   File "/data/dingpeigeng/project/PointAvatar/code/../code/scripts/test.py", line 176, in run
>     model_outputs = self.model(model_input)
>   File "/data/dingpeigeng/anaconda3/envs/point-avatar/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data/dingpeigeng/project/PointAvatar/code/../code/model/point_avatar_model.py", line 176, in forward
>     images = self._render(transformed_point_cloud, cameras)
>   File "/data/dingpeigeng/project/PointAvatar/code/../code/model/point_avatar_model.py", line 96, in _render
>     images, weights = self.compositor(
> ValueError: too many values to unpack (expected 2)
>

**Comment by zhengyuf** [comment]
please check our readme file on Pytorch 3D installation.
