### ISSUE TITLE
Empty rgb_gt using default data and code

### ISSUE THREAD

**Issue by doublexxking** [zhengyuf/PointAvatar#15]
As title mentioned, I use yufeng and marcel to train model, I change noting.
The first eval rendering is shown as following:
![epoch_0000_1](https://github.com/zhengyuf/PointAvatar/assets/11947126/7a735516-08cb-4822-9138-de80f584b307)

The following images are all white. 
![epoch_0001_1](https://github.com/zhengyuf/PointAvatar/assets/11947126/12b7ef91-6934-4962-acfc-18b388f5389e)

Do you know what the problem is ?

**Comment by zhengyuf** [comment]
It seems like the training data is all white, and the foreground masks are all empty. Maybe you can check the data loading pipeline, but this issue has never happened for me, so I’m sorry but I don’t know the exact reason.

**Comment by doublexxking** [comment]
Thanks for your reply, I change load_rgb and load_mask using cv2, it seems OK now.
different imageio.imread cause problem
