### ISSUE TITLE
Curiosity: why not use Pulsar points renderer in Pytorch3d?

### ISSUE THREAD

**Issue by nlml** [zhengyuf/PointAvatar#16]
Hi there,

Thanks for releasing your code.

I'm looking into avatars + point rendering in Pytorch3D at the moment and noticed there is Pulsar, which is supposedly faster. But it seems you didn't use this. Could you give any insights as to why not?

Thanks!
Liam

**Comment by zhengyuf** [comment]
Hi Liam,

We've given it a brief try and changing to Pulsar renderer didn't work easily. But I do agree that we're using a very basic point renderer, and using recent, more advanced renderers could be a promising direction!

Yufeng

**Comment by nlml** [comment]
@zhengyuf thanks!
