### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by muses0229** [zhengyuf/PointAvatar#18]

**Comment by muses0229** [comment]
Here is my command for training:
CUDA_VISIBLE_DEVICES=0 nohup python scripts/exp_runner.py --conf ./confs/subject1.conf --is_continue > train.log 2>&1 &

**Comment by NewtOliver** [comment]
> Here is my command for training: CUDA_VISIBLE_DEVICES=0 nohup python scripts/exp_runner.py --conf ./confs/subject1.conf --is_continue > train.log 2>&1 &

Thank you for your answer, but what does '> train.log 2>&1 &' mean?

**Comment by NewtOliver** [comment]
> Thanks for the great work.I use a RTX 3090 for training,and I have set train.max_points_training and point_cloud.max_points to 240000,but I still meet OOM problem,even I decrease batch_size to 1 it still happen.Here is the detailed issue: current point number: 89872 old radius: 0.00950290560722351, new radius: 0.0071271792054176325 old points: 89872.0, new points: 179744 Traceback (most recent call last): File "/home/yejr/Digital_Avater/PointAvatar-master/code/scripts/exp_runner.py", line 35, in runner.run() File "/home/yejr/Digital_Avater/PointAvatar-master/code/../code/scripts/train.py", line 405, in run loss_output = self.loss(model_outputs, ground_truth) File "/media/data4/yejr/conda_env/point-avatar/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/home/yejr/Digital_Avater/PointAvatar-master/code/../code/model/loss.py", line 126, in forward gt_shapedirs * 10, RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 23.70 GiB total capacity; 21.62 GiB already allocated; 10.56 MiB free; 21.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF Could you tell me how should I do?

I have the same problem, have you solved it?

**Comment by Arthur-Evans** [comment]
Hello，Are you still possessing the original data set? Can you send me one ? There is something wrong with the data set provided by the author and cannot be downloaded. Thanks.

**Comment by zhengyuf** [comment]
See here for OOM issue #1
