### ISSUE TITLE
How to relight based on given background images?

### ISSUE THREAD

**Issue by aboutx** [zhengyuf/PointAvatar#2]
Hello, congradulations for such nice job! However, I am confused about how to relight in novel scenes.
Would you mind open source the relight code?
Thanks very much!

**Comment by zhengyuf** [comment]
Hi,

The relight code which I used to generate the result in the video is only a directional light. I didn't implement relighting given environment maps, unfortunately...

best,
Yufeng

**Comment by aboutx** [comment]
Oh, get it. Thanks for your reply!
I would like to know how long it takes to relight an image for given directional light?

**Comment by zhengyuf** [comment]
Sorry for the late reply 
The rendering time depends on the number of points, but if we assume that the normal directions are pre-calculated, it should be really fast.
With 292k points, it takes 0.045s per frame.

**Comment by aboutx** [comment]
> Sorry for the late reply The rendering time depends on the number of points, but if we assume that the normal directions are pre-calculated, it should be really fast. With 292k points, it takes 0.045s per frame.

Oh, so pointavatar is actually real-time! Nice job! Thank you very much!

**Comment by zhengyuf** [comment]
heyy

To be clear, this time didn't include the animation though (deformation MLP query and normal transformation). Only relighting and rendering. 

best,

**Comment by aboutx** [comment]
Oh, sure. Then I'm wondering how long does Pointavatar take to render an image for given pose, expression and lighting (with single 3090 gpu)?

**Comment by aboutx** [comment]
Looking for your reply :)
