### ISSUE TITLE
about datasets  you don't have permission to access this resource when I try to run download.bash.  What's wrong???

### ISSUE THREAD

**Issue by Arthur-Evans** [zhengyuf/PointAvatar#20]
I have configured all the environments. There is no functorch0.1.0 in pytorch1.11.0 under Windows. I only need to download pytorch1.12.1 and functorch0.2.0.
But when I configured all the environments and ran the file downdata.bash to download the database, it prompted "HTTP request sent, awaiting response... 404 Not Found". I searched directly in the browser based on this URL and found that I did not have permission to access the resource. , the browser prompts 403 and Forbidden. I was able to download data successfully in December, why not now? ? ? ? ? What happened?
![屏幕截图 2024-01-30 000638](https://github.com/zhengyuf/PointAvatar/assets/76278246/c074c499-71f8-4bbf-bd31-8f09b4b41f9b)
![屏幕截图 2024-01-30 000716](https://github.com/zhengyuf/PointAvatar/assets/76278246/45c36b70-b259-4193-8fca-89354143f9ed)
![屏幕截图 2024-01-30 000710](https://github.com/zhengyuf/PointAvatar/assets/76278246/cca242a9-b3aa-4a0c-8c79-811c6ae0554d)

**Comment by zhengyuf** [comment]
Oops, I anonymized the subjects' links and renamed them to subject1, subject2 and subject3. But I forgot to update download_data.bash.
I'll update it.
