### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by saboorniazi** [zhengyuf/PointAvatar#21]
shell command : scripts/exp_runner.py --conf ./confs/subject1.conf --is_eval
Loading data ...
Finish loading data ...
creating the FLAME Decoder
Canonical expression:  tensor([[ 0.1662,  0.3928,  0.0172,  0.1365, -0.1178,  0.4555, -0.1693, -0.4088,
          0.1085,  0.5834, -0.6895, -0.1363, -0.3936,  0.5161, -0.0302, -0.0410,
         -0.3208, -0.1618,  0.0507,  0.2476, -0.0370, -0.2849,  0.1857, -0.1914,
         -0.2390,  0.0215,  0.0572,  0.0187, -0.1371, -0.2072, -0.1512, -0.0693,
          0.1041, -0.1097,  0.0102, -0.0312,  0.0773, -0.0876, -0.0166,  0.0174,
         -0.0392,  0.0148, -0.0696,  0.0560, -0.1038, -0.0079, -0.0469,  0.0922,
          0.0014,  0.0480]])
/Users/saboor/anaconda3/envs/head/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
current point number:  400
current point number:  310718
Expression variance:  None
Optimizing test expressions
Optimizing tracking, this is a slow process which is only used for calculating metrics. 
for qualitative animation, set optimize_expression and optimize_camera to False in the conf file.
[0, 1, 2, 3, 4, 5, 6]
/Users/saboor/anaconda3/envs/head/lib/python3.9/site-packages/torch/_functorch/deprecated.py:88: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.jacfwd is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.jacfwd instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('jacfwd')
/Users/saboor/anaconda3/envs/head/lib/python3.9/site-packages/torch/_functorch/deprecated.py:61: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
Traceback (most recent call last):
  File "/Users/saboor/Documents/PointAvatar/code/scripts/exp_runner.py", line 51, in <module>
    runner.run()
  File "/Users/saboor/Documents/PointAvatar/code/../code/scripts/test.py", line 176, in run
    model_outputs = self.model(model_input)
  File "/Users/saboor/anaconda3/envs/head/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/saboor/anaconda3/envs/head/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/saboor/Documents/PointAvatar/code/../code/model/point_avatar_model.py", line 177, in forward
    images = self._render(transformed_point_cloud, cameras)
  File "/Users/saboor/Documents/PointAvatar/code/../code/model/point_avatar_model.py", line 96, in _render
    images, weights = self.compositor(
ValueError: too many values to unpack (expected 2)

**Comment by zhengyuf** [comment]
Hi, 

we use a slightly modified version of Pytorch3D. You can follow the instructions in our README to install it.
