### ISSUE TITLE
Could you share some outputs?

### ISSUE THREAD

**Issue by Zvyozdo4ka** [zhengyuf/PointAvatar#22]
Hello.
Thanks for sharing your work.

1. Since i could not install your pytorch3d version, neither by using your links, nor dockers, i want to ask you if you can share outputs of Marcel and Yufeng subjects?

2. how to get such good reconstruction?

![image](https://github.com/zhengyuf/PointAvatar/assets/74532816/97c907b0-88df-460f-8e87-45de07ede6ef)

3. inputs in your work video file, right? 
And the output reconstructed point cloud in flame coordinate system?

4. how did you get vertices and point cloud in flame canonical space?
Why did you chose pose with open month for flame canonical space? for facial landmarks?

Thanks in advance for your response.

**Comment by zhengyuf** [comment]
hi,
1. The pretrained models linked in the readme already contain the trained point clouds and all rendered images for the test frames. Also, our Pytorch3D version only contains a small modification, and it doesn't have extra requirements compared to the original, as long as you can install Pytorch3D from source, you should be able to install our version.
2. This is just the result from Pointavatar without modification.
3. yes
4. the open mouth pose is for easier deformation around the mouth/teeth region. However, we do admit that PointAvatar's quality for teeth is still not ideal.
