### ISSUE TITLE
RuntimeError: wrapper->level().value() <= cur_levelINTERNAL ASSERT FAILED at "/__w/functorch/functorch/functorch/csrc/DynamicLayer.cpp":267, please report a bug to PyTorch. escaped?

### ISSUE THREAD

**Issue by longphamkhac** [zhengyuf/PointAvatar#24]
Tks for your brilliant work, when running the point_avatar_model.py, I get this error from the self.deformer_network.query_weights(pnts_c) of the get_rbg_value_functorch function? Do you have any ideas about this error?

**Comment by zhengyuf** [comment]
Hi, can you include the error message?

**Comment by zhengyuf** [comment]
This seems to be a functorch error. I couldn't find an answer with a light search. If the problem persists, consider raising an 
issue in their [repo](https://github.com/pytorch/functorch/issues).

I did find [this](https://pytorch.org/docs/stable/func.migrating.html), which seems to say that some functions of functorch are merged to pytorch if you use torch >= 2.0.

Specifically, 
functorch.jacfwd  -> torch.func.jacfwd()
functorch.vmap -> torch.vmap() or torch.func.vmap()

However, I'm afraid there will be other incompatibilities when switching to torch>2.0. I think Pytorch3D wouldn't be compatible for a start. 😢
