### ISSUE TITLE
Clarification on Camera Intrinsics Values in Dataset

### ISSUE THREAD

**Issue by LongDan15** [zhengyuf/PointAvatar#26]
Hello,

I hope this message finds you well. I am currently working with your dataset and have encountered some confusion regarding the camera intrinsic parameters labeled as "intrinsics": [-3.0071769921875, 2.947134375, 0.5106301328125, 0.494593544921875]. You have mentioned that these intrinsics correspond to the camera focal lengths (fx, fy) and principal point offsets (cx, cy).

I am curious as to why the values for the focal lengths (fx, fy) are around 3. Typically, these are expressed in pixel units, and even if normalized, wouldn't they range between 0 and 1? This has been quite puzzling for me. Additionally, I noticed that the focal lengths are multiplied by 2 when they are read from the dataset, and if fx is less than 0, it is multiplied by -1 to convert it to a positive number. Could you please provide some insight into the reasoning behind these values and calculations?

Thank you for your time and assistance. I appreciate any clarification you can provide.

**Comment by zhengyuf** [comment]
Hi,

The fx and fy are not expressed in pixel units, instead, they assume that the image boundary is [0,1]. Multiplying the focal length by 2, we transform them into the NDC coordinate system used by Pytorch3D (https://pytorch3d.org/docs/cameras).

Pytorch3D also expects focal lengths to be positive. To satisfy this, we can negate fx, and flip the x-axis of the extrinsic matrix. By doing so, the final projection matrix (multiplication of the extrinsic and intrinsic matrix ) doesn't change, and we can have positive focal lengths.

Yufeng
