### ISSUE TITLE
Where the code confusing me

### ISSUE THREAD

**Issue by JACKYLUO1991** [zhengyuf/PointAvatar#5]
1. in FLAME.py, why is the **factor** multiplied by 4?
2. in deformer_network.py, why **lbs_weights_exp=torch.exp(20 * lbs_weights)**?  What is the purpose of 20?
3. What is the format of pose correctives? What are the pose used?

**Comment by zhengyuf** [comment]
1. This is just because the preprocessing script scaled the FLAME mesh by 4.

2. The purpose of 20 is to make the LBS weight learn faster in practice. 

3. They are formatted exactly the same as FLAME. The pose used is FLAME pose as well.
