### ISSUE TITLE
Occupancy Field and SDF

### ISSUE THREAD

**Issue by HyunsooCha** [zhengyuf/PointAvatar#7]
Hi

Thank you for your excellent work.
I would like to ask what's the difference between the IMavatar and PointAvatar in the geometry network. IIRC, IMavatar used the occupancy field for the geometry network, and PointAvatar used the SDF for the geometry network. However, I cannot find the difference between the geometry_network.py files from each code. I know that PointAvatar used Eikonal loss for SDF, and IMavatar didn't. Is the only difference between the two codes Eikonal loss?

Thank you so much for your reply in advance.

**Comment by zhengyuf** [comment]
Hey,

Indeed, the eikonal loss is the only difference in implementation.

**Comment by HyunsooCha** [comment]
Thank you for your confirmation.

Closed
