### ISSUE TITLE
zero n_points in training

### ISSUE THREAD

**Issue by Mprjct** [zhengyuf/PointAvatar#9]
Hi

Thank you for your excellent work.
During the training, I received the following message and error. There will be a decrease in the number of points from 400 to zero.

"Pruning points, original: 400, new: 0" 

File "/code/model/point_avatar_model.py", line 156, in forward
    pose_feature=pose_feature.unsqueeze(1).expand(-1, n_points, -1).reshape(total_points, -1),
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by zhengyuf** [comment]
hi,

Are you using your own data? I suspect that something is wrong with your camera, or the foreground masks, which results in the points not being correctly projected onto your image.

best,
Yufeng

**Comment by Mprjct** [comment]
Thanks for your reply.
No, I used default datasets like marcel and yufeng. It would be most helpful if you could advise me on which part of the code to check for this error. I evaluated the pretrained model correctly.
Thanks very much!

**Comment by zhengyuf** [comment]
What did you change from the default?

**Comment by Mprjct** [comment]
I reduced the number of frames in the flame_params.json file due to hardware limitations.

**Comment by Mprjct** [comment]
The first epoch worked, but I got this error at the beginning of the second epoch.

**Comment by Mprjct** [comment]
The error has been resolved by removing the prunning portion of the training code. What impact do you think it will have on the results?

**Comment by zhengyuf** [comment]
I couldn't tell the problem. Maybe check the rendered images?

**Comment by javadmozaffari** [comment]
hi,
there is a problem with "self.compositor = AlphaCompositor()" in point_avatar_model.py. this class have a one output but in the line 96 we expect two output (images, weights = self.compositor).

**Comment by zhengyuf** [comment]
hi,

We modified Pytorch3d a bit. Please check the readme file on how to install our version.

**Comment by Zvyozdo4ka** [comment]
> hi,
> 
> We modified Pytorch3d a bit. Please check the readme file on how to install our version.

could you please specify what exactly you changed in pytorch3d? 

it is always a failure to install your version of pytorch3d, even though:

```
torch.cuda.is_available()
True
```
